### ISSUE TITLE
Code in get_expert_scores.py Doesn't Store the Scoring Result

### ISSUE THREAD

**Issue by dog14230pp** [deepseek-ai/ESFT#7]
Dear authors,
Really thanks for releasing the code for the excellent work ESFT.

Recently, I want to run the code on my own dataset. However, when I run this code "get_expert_scores.py", I found that I can not find any code about storing the results for expert scores, which means that I can't get each experts score [(link)](https://github.com/deepseek-ai/ESFT/blob/main/scripts/expert/get_expert_scores.py#L30).

Could you add the missing code for this part? Or tell me if I miss something
Many Thanks!

**Comment by ZihanWang314** [comment]
Can you replace your modeling file with https://huggingface.co/deepseek-ai/ESFT-vanilla-lite/blob/main/modeling_deepseek.py ? Please note that this file is different from the training configuration file since it has an expert result logging part.

**Comment by dog14230pp** [comment]
The problem has been solved! Thanks~
